#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-SensorX" id="HB-UNI-SensorX">
DEVICE="HB-UNI-Sensor1"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Universalsensor1 (Wetterdaten)"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sensor1.png
DEVICE_THUMB=hb-uni-sensor1_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sensor1*.xml

#------------------------------------------------------------------------------
# Edit DEVDB.tcl
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Edit webui.js
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

#------------------------------------------------------------------------------
# Edit stringtable_de.txt
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="WEATHER|Abs_Luftfeuchte\t\${stringTableWeather_AbsLuftfeuchte}"
if [ -z "`cat $stringtable_deFile | grep \"Abs_Luftfeuchte\"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="WEATHER|Taupunkt\t\${stringTableWeather_Taupunkt}"
if [ -z "`cat $stringtable_deFile | grep \"Taupunkt\"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

#------------------------------------------------------------------------------
# Edit German translate.lang.stringtable.js
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableWeather_AbsLuftfeuchte\" : \"Abs. Luftfeuchte\","
if [ -z "`cat $translate_deFile | grep \"stringTableWeather_AbsLuftfeuchte\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableWeather_Taupunkt\" : \"Taupunkt\","
if [ -z "`cat $translate_deFile | grep \"stringTableWeather_Taupunkt\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
