#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <id="HB-Sec-WDS-2">
DEVICE="HB-Sec-WDS-2"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Wassermelder"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-sec-wds-2.png
DEVICE_THUMB=hb-sec-wds-2_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-sec-wds-2*.xml

#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
        sed -i "/\($DEVICE\)/d" $webuiFile
fi

#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILE

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
