#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-SensorX" id="HB-UNI-SensorX">
DEVICE="HB-UNI-Sensor1"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Universalsensor1 (Wetterdaten)"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sensor1.png
DEVICE_THUMB=hb-uni-sensor1_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sensor1*.xml

#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
        sed -i "/\($DEVICE\)/d" $webuiFile
fi

#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILE

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

#------------------------------------------------------------------------------
# Undo stringtable_de.txt
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deSearch="WEATHER|Abs_Luftfeuchte"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

stringtable_deSearch="WEATHER|Taupunkt"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

#------------------------------------------------------------------------------
# Undo German translate.lang.stringtable.js
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"

translate_deSearch="stringTableWeather_AbsLuftfeuchte"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

translate_deSearch="stringTableWeather_Taupunkt"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
