#!/bin/sh
# WebUI icon used from http://icons8.com 

source ./addon/params 2>/dev/null

RC_DIR=/usr/local/etc/config/rc.d
WWW_DIR=/usr/local/etc/config/addons/www/$ADDON_NAME
ADDON_DIR=/usr/local/addons/$ADDON_NAME

# mount /usr/local if not already mounted
mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# Startscript anlegen
cp -af rc.d/$ADDON_NAME ${RC_DIR}/
chmod +x ${RC_DIR}/$ADDON_NAME

# Addon-Verzeichnis anlegen
mkdir -p ${ADDON_DIR}
cp -af addon/* ${ADDON_DIR}
chmod 755 ${ADDON_DIR}

# Symbolic Links
rm -rf ${WWW_DIR}
ln -sf ${ADDON_DIR} ${WWW_DIR}

# Installationsstatus entfernen, um Installation nach Reboot zu erzwingen
rm -f ${ADDON_DIR}/installed

sync

if [ "$1" = "HM-RASPBERRYMATIC" ] || [ "$1" = "CCU3" ]; then
  exit 10
fi
