#!/bin/bash

#------------------------------------------------------------------------------
model=0
version=0
build=0
builddate=0
PATCHVERSION=0
FW_VERSION=0
check_ccu_fw_version()
{
	model=`grep VERSION /boot/VERSION     | awk -F'[=.]' {'print $2'}`
	version=`grep VERSION /boot/VERSION   | awk -F'[=.]' {'print $3'}`
	build=`grep VERSION /boot/VERSION     | awk -F'[=.]' {'print $4'}`
	builddate=`grep VERSION /boot/VERSION | awk -F'[=.]' {'print $5'}`
    
    FW_VERSION=$model.$version.$build.$builddate

 	if [ $model -ge 2 ] && [ $version -ge 45 ]; then
  		PATCHVERSION=2
 	else
  		PATCHVERSION=1
 	fi
}

#------------------------------------------------------------------------------
MONIT=0
check_monit()
{
  	MONIT=`ps -ef|grep \/usr\/bin\/monit|grep -v grep|wc -l`
}

#------------------------------------------------------------------------------
REGA=0
check_rega()
{
  	REGA=`ps -ef|grep \/bin\/ReGaHss|grep -v grep|wc -l`
}

#------------------------------------------------------------------------------
RFD=0
check_rfd()
{
  	RFD=`ps -ef|grep \/bin\/rfd|grep -v grep|wc -l`
}

#------------------------------------------------------------------------------
logToFile()
{
	now=$(date +"%d.%m.%Y %H:%M:%S")
  	echo "$now $2" >> $1
}
