#!/bin/bash

#------------------------------------------------------------------------------
MODEL=0
VERSION=0
BUILD=0
PATCHVERSION=0
check_ccu_fw_version()
{
	MODEL=`grep VERSION /boot/VERSION   | awk -F'[=.]' {'print $2'}`
	VERSION=`grep VERSION /boot/VERSION | awk -F'[=.]' {'print $3'}`
	BUILD=`grep VERSION /boot/VERSION   | awk -F'[=.]' {'print $4'}`

 	if [ $MODEL -ge 3 ] && [ $VERSION -ge 45 ]; then
  		PATCHVERSION=2
 	else
  		PATCHVERSION=1
 	fi
}

#------------------------------------------------------------------------------
MONIT=0
check_monit()
{
  	MONIT=`ps -ef|grep \/usr\/bin\/monit|grep -v grep|wc -l`
}

#------------------------------------------------------------------------------
REGA=0
check_rega()
{
  	REGA=`ps -ef|grep \/bin\/ReGaHss|grep -v grep|wc -l`
}

#------------------------------------------------------------------------------
RFD=0
check_rfd()
{
  	RFD=`ps -ef|grep \/bin\/rfd|grep -v grep|wc -l`
}

#------------------------------------------------------------------------------
logToFile()
{
	now=$(date +"%d.%m.%Y %H:%M:%S")
  	echo "$now $2" >> $1
}
