#!/bin/sh

source ./params 2>/dev/null

#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
        sed -i "/\($DEVICE\)/d" $webuiFile
fi

#------------------------------------------------------------------------------
# remove device_xml links
rm -f ${FIRMWARE_DIR}/${ADDON_NAME}*

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
