#!/bin/sh
# WebUI icon used from http://icons8.com 

ADDON_NAME=`basename "$0"`

source /usr/local/addons/${ADDON_NAME}/params 2>/dev/null

ADDON_DIR=/usr/local/addons/${ADDON_NAME}
WWW_DIR=/etc/config/addons/www/${ADDON_NAME}
LOGFILE=/var/log/$ADDON_NAME.log
ERRFILE=/var/log/$ADDON_NAME.err

case "$1" in
	""|start)
		echo 'Starting...'
		if [ ! -f ${ADDON_DIR}/installed ] || [ ! -f ${FIRMWARE_FILE} ]; then
            # ACHTUNG, custom devices sind nach RM firmware update weg (befinden sich aber im Posteingang)
            # Jerome:
            # Das Problem ist Folgendes, nach einem Firmware-Update  fährt das System erstmal unmodifiziert hoch, ..., rfd startet, ReGaHss startet.
            # Danach erst werden die Addon-Skripts ausgeführt, somit auch dein rc.d/hb-uni-sensor1.
            # RFD und ReGaHss laufen dabei jedoch schon und sie wurden gestartet, bevor sie deine Custom-Geräte kennen konnten.
            # Die Geräte bekommen dabei das "dirty"-Flag und landen im Posteingang. 
            # Sie dürften auch aus allen Programmen rausfliegen. Bin mir aber nicht 100% sicher.
            # Aus diesem Grund halte ich vor der Installation meines Addons die beiden Dienste an und starte sie erst zum Schluss wieder.
            /etc/init.d/S70ReGaHss stop
            /etc/init.d/S61rfd stop
			cd ${ADDON_DIR}
			./install > $LOGFILE 2>$ERRFILE
            /etc/init.d/S61rfd start
            /etc/init.d/S70ReGaHss start
		else
			echo "Nothing to do for $DEVICE"
		fi
	;;

	stop)
		echo "Nothing to stop..."
	;;

	uninstall)
    		cd ${ADDON_DIR}
    		./uninstall > $LOGFILE 2>$ERRFILE
    		cd /
    		rm -rf $ADDON_DIR
    		rm -rf $WWW_DIR
    	;;
  
	restart|reload)
  	  # Operations to stop and start (restart) the addon
  	  stop
  	  sleep 2
  	  start
    	;;

	info)
		echo "Info: <b>$DEVICE Addon</b><br>"
		echo "Info: <b>CCU2 & RaspberryMatic</b><br>"
		echo "Info: (c) 2018-2019 TomMajor<br>"
		echo "Info: ${ADDON_INFO_LINK}"
		echo "Version: $(cat ${ADDON_DIR}/VERSION)"
		echo "Name: $DEVICE"
		echo "Operations: uninstall"
		#echo "Config-Url: ${CONFIG_URL}"
		echo "Update: /addons/$ADDON_NAME/update-check.cgi"
	;;
	
	*)
		echo "Usage: $ADDON_NAME {start|stop|restart|info|uninstall}" >&2
		exit 1
    	;;

esac

exit $?
