#!/bin/sh

ADDON_NAME=hbunisensor1
ADDON_DIR=/usr/local/addons/$ADDON_NAME

mount -o remount,rw /

##########################################
### New device HB-UNI-Sensor1 ###
##########################################

device="HB-UNI-Sensor1"
device_img=hb-uni-sensor1.png
device_thumb=hb-uni-sensor1_thumb.png

### Copy new devices Files ###
cp -a firmware/rftypes/* /firmware/rftypes/

### Copy new images ###
cp -ar www/config/img/devices /www/config/img/

chown root:root /www/config/img/devices/250/$device_img
chmod 755 /www/config/img/devices/250/$device_img
chown root:root /www/config/img/devices/50/$device_thumb
chmod 755 /www/config/img/devices/50/$device_thumb

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert=""
devdescrInsert="$devdescrInsert $device {{50 \/config\/img\/devices\/50\/$device_thumb} {250 \/config\/img\/devices\/250\/$device_img}} "

if [ -z "`cat $devdescrFile | grep \"$device\"`" ]; then
	cp -a $devdescrFile $ADDON_DIR/DEVDB.tcl.save
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="$webuiInsert DEV_HIGHLIGHT['$device'] = new Object();\n"
webuiInsert="$webuiInsert DEV_LIST.push('$device');\n"
webuiInsert="$webuiInsert DEV_DESCRIPTION['$device']='Universal Sensor';\n"
webuiInsert="$webuiInsert DEV_PATHS['$device'] = new Object();\n"
webuiInsert="$webuiInsert DEV_PATHS['$device']['50'] = '\/config\/img\/devices\/50\/$device_thumb';\n"
webuiInsert="$webuiInsert DEV_PATHS['$device']['250'] = '\/config\/img\/devices\/250\/$device_img';\n"

if [ -z "`cat $webuiFile | grep \"$device\"`" ]; then
	cp -a $webuiFile $ADDON_DIR/webui.js.save
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

sync

mount -o remount,ro /

# /etc/init.d/S61rfd restart

touch $ADDON_DIR/installed