#!/bin/sh
#
# $1 install/uninstall
# $2 ADDON_NAME
# $3 PATCHSUBDIR_VERSION
# $4 FW_VERSION

ADDON_NAME=$2
PATCHSUBDIR_VERSION=$3
FW_VERSION=$4

ADDON_DIR=/usr/local/addons/${ADDON_NAME}
LOG_DIR=${ADDON_DIR}/log
LOGFILE=$LOG_DIR/inst.log
ERRFILE=$LOG_DIR/inst.err
BACKUP_DIR=${ADDON_DIR}/backup_${FW_VERSION}

PATCHFILE1=/www/rega/esp/functions.fn
PATCHFILE2=/www/config/ic_common.tcl
PATCHFILE3=/www/webui/webui.js
PATCHFILE4=/www/rega/pages/tabs/admin/views/programs.htm
PATCHFILE5=/www/rega/esp/side.inc

convert_lf() 
{
  filename=`sed -n '2p' $1 | sed 's/+++ .\/patchsource//g' | awk {'print $1'}`
  cmpresult=`unix2dos < $filename | cmp - $filename`
  if [ "$cmpresult" ]; then
    cmpresult=`dos2unix < $1 | cmp - $1`
    if [ "$cmpresult" ]; then
      echo "dos2unix conversion needed for $1" | tee -a $LOGFILE
      dos2unix $1 | tee -a $LOGFILE | tee -a $ERRFILE
    fi  
  fi
}

case "$1" in
    install)
    
        echo "patchworker ($1) ($2) ($3) ($4)" | tee -a $LOGFILE
    
        # beim ersten Mal auf neuer Firmware die zu patchenden Originalfiles sichern und (weiter unten) patchen
        if [ ! -f ${BACKUP_DIR}/saved ]; then
            echo "First time install, save backup $FW_VERSION" | tee -a $LOGFILE
            mkdir -p ${BACKUP_DIR}
            cp -af ${PATCHFILE1} ${BACKUP_DIR} >> $LOGFILE 2>>$ERRFILE
            cp -af ${PATCHFILE2} ${BACKUP_DIR} >> $LOGFILE 2>>$ERRFILE
            cp -af ${PATCHFILE3} ${BACKUP_DIR} >> $LOGFILE 2>>$ERRFILE
            cp -af ${PATCHFILE4} ${BACKUP_DIR} >> $LOGFILE 2>>$ERRFILE
            cp -af ${PATCHFILE5} ${BACKUP_DIR} >> $LOGFILE 2>>$ERRFILE
            touch ${BACKUP_DIR}/saved
        # sonst ist es wahrscheinlich eine Update-Installation
        # in diedem Fall die Originalfiles einfach zurückholen und (weiter unten) erneut patchen
        else
            echo "update-install, restore backup $FW_VERSION" | tee -a $LOGFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE1) $(dirname $PATCHFILE1) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE2) $(dirname $PATCHFILE2) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE3) $(dirname $PATCHFILE3) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE4) $(dirname $PATCHFILE4) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE5) $(dirname $PATCHFILE5) >> $LOGFILE 2>>$ERRFILE
        fi

        # Patches
        cd /www
        
        # Patches common
        echo "Apply common patches" | tee -a $LOGFILE
        patchsubdir=common
        for patchfile in /usr/local/addons/${ADDON_NAME}/patch/$patchsubdir/* ; do
            echo "Applying <$patchsubdir> patch file $(basename $patchfile)" | tee -a $LOGFILE
            convert_lf $patchfile
            patch -N -p3 -i $patchfile >> $LOGFILE 2>>$ERRFILE
        done
        
        # Patches firmware dependend
        echo "Apply firmware dependend patches" | tee -a $LOGFILE
        patchsubdir=${PATCHSUBDIR_VERSION}
        for patchfile in /usr/local/addons/${ADDON_NAME}/patch/$patchsubdir/* ; do
            echo "Applying <$patchsubdir> patch file $(basename $patchfile)" | tee -a $LOGFILE
            convert_lf $patchfile
            patch -N -p3 -i $patchfile >> $LOGFILE 2>>$ERRFILE
        done

    ;;
    
    uninstall)
    
        echo "patchworker ($1) ($2) ($3) ($4)" | tee -a $LOGFILE
    
        # die gesicherten Originalfiles zurückschreiben
        if [ -f ${BACKUP_DIR}/saved ]; then
            echo "uninstall, restore backup $FW_VERSION" | tee -a $LOGFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE1) $(dirname $PATCHFILE1) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE2) $(dirname $PATCHFILE2) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE3) $(dirname $PATCHFILE3) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE4) $(dirname $PATCHFILE4) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE5) $(dirname $PATCHFILE5) >> $LOGFILE 2>>$ERRFILE
        fi
        
    ;;
    
    *)
    ;;
    
esac
