#!/bin/sh

DEVICE="HB-OU-MP3-LED"
DEVICE_IMG=hb-ou-mp3-led.png
DEVICE_THUMB=hb-ou-mp3-led_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-ou-mp3-led.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="SIGNAL_LED|HB_LED_COUNT"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="HB_INTERRUPT_RUNNING"
sed -i "/\($webuiSearch\)/d" $webuiFile

stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="SIGNAL_LED|HB_LED_COUNT"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="HB_INTERRUPT_RUNNING"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbLedCount"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableHbInterruptRunning"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deFile="/www/webui/js/lang/de/translate.lang.extension.js"
translate_deSearch="lblHbIterations"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f /www/config/easymodes/signal_hbchime_ch_link.tcl
rm -f /www/config/easymodes/signal_hbled_ch_link.tcl
rm -rf /www/config/easymodes/SIGNAL_CHIMEHB
rm -rf /www/config/easymodes/SIGNAL_LEDHB

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
