#!/bin/sh

source ./params 2>/dev/null
source ./functions 2>/dev/null

ADDON_DIR=/usr/local/addons/${ADDON_NAME}
LOGFILE=$ADDON_DIR/inst.log
ERRFILE=$ADDON_DIR/inst.err

PATCHFILE1=/www/config/ic_common.tcl
PATCHFILE2=/www/rega/esp/functions.fn
PATCHFILE3=/www/rega/esp/side.inc
PATCHFILE4=/www/rega/pages/tabs/admin/views/programs.htm

check_ccu_fw_version
BACKUP_DIR=${ADDON_DIR}/backup_${FW_VERSION}

case "$1" in
    install)
    
        logToFile $LOGFILE "extra ($1)"

        logToFile $LOGFILE "Found firmware version $FW_VERSION - using patchversion $PATCHVERSION"
    
        # beim ersten Mal auf neuer Firmware die zu patchenden Originalfiles sichern und (weiter unten) patchen
        if [ ! -f ${BACKUP_DIR}/saved ]; then
            logToFile $LOGFILE "First time install, save backup $FW_VERSION"
            mkdir -p ${BACKUP_DIR}
            cp -af ${PATCHFILE1} ${BACKUP_DIR} >> $LOGFILE 2>>$ERRFILE
            cp -af ${PATCHFILE2} ${BACKUP_DIR} >> $LOGFILE 2>>$ERRFILE
            cp -af ${PATCHFILE3} ${BACKUP_DIR} >> $LOGFILE 2>>$ERRFILE
            cp -af ${PATCHFILE4} ${BACKUP_DIR} >> $LOGFILE 2>>$ERRFILE
            touch ${BACKUP_DIR}/saved
        # sonst ist es wahrscheinlich eine Update-Installation
        # in diedem Fall die Originalfiles einfach zurückholen und (weiter unten) erneut patchen
        else
            logToFile $LOGFILE "update-install, restore backup $FW_VERSION"
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE1) $(dirname $PATCHFILE1) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE2) $(dirname $PATCHFILE2) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE3) $(dirname $PATCHFILE3) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE4) $(dirname $PATCHFILE4) >> $LOGFILE 2>>$ERRFILE
        fi

        # Patches
        cd /www
        
        # Patches common
        logToFile $LOGFILE "Apply common patches"
        patchsubdir=common
        for file in /usr/local/addons/${ADDON_NAME}/patch/$patchsubdir/* ; do
            logToFile $LOGFILE "Applying <$patchsubdir> patch file $(basename $file)"
            patch -N -p3 -i $file >> $LOGFILE 2>>$ERRFILE
        done
        
        # Patches firmware dependend
        logToFile $LOGFILE "Apply firmware dependend patches"
        if [ $PATCHVERSION -le 1 ]; then
            patchsubdir=le_343
        else
            patchsubdir=ge_345
        fi
        
        for file in /usr/local/addons/${ADDON_NAME}/patch/$patchsubdir/* ; do
            logToFile $LOGFILE "Applying <$patchsubdir> patch file $(basename $file)"
            patch -N -p3 -i $file >> $LOGFILE 2>>$ERRFILE
        done

        # Generate new device_xml links, no copy anymore
        for file in /usr/local/addons/${ADDON_NAME}${FIRMWARE_DIR}/* ; do
            rm -f ${FIRMWARE_DIR}/$(basename $file)
            ln -s $file ${FIRMWARE_DIR}/$(basename $file)
            chmod 644 $file
        done
        
        ### Create Symlink to include own js file
        logToFile $LOGFILE "(Re-)Creating symlinks for jp_webui_inc.js"
        [[ ! -f /www/webui/js/extern/jp_webui_inc.js ]] && ln -s /usr/local/addons/${ADDON_NAME}/js/jp_webui_inc.js /www/webui/js/extern/jp_webui_inc.js
        
        # # Copy new image files
        cd ${ADDON_DIR}
        cp -ar www/* /www/
        chown root:root /www/config/img/devices/250/${ADDON_NAME}*
        chmod 755 /www/config/img/devices/250/${ADDON_NAME}*
        chown root:root /www/config/img/devices/50/${ADDON_NAME}*
        chmod 755 /www/config/img/devices/50/${ADDON_NAME}*
        chown root:root /www/ise/img/icons_hm_dis_ep_wm55/24/*
        chmod 755 /www/ise/img/icons_hm_dis_ep_wm55/24/*
        
    ;;
    
    uninstall)
    
        logToFile $LOGFILE "extra ($1)"
    
        # die gesicherten Originalfiles zurückschreiben
        if [ -f ${BACKUP_DIR}/saved ]; then
            logToFile $LOGFILE "uninstall, restore backup $FW_VERSION"
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE1) $(dirname $PATCHFILE1) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE2) $(dirname $PATCHFILE2) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE3) $(dirname $PATCHFILE3) >> $LOGFILE 2>>$ERRFILE
            cp -af ${BACKUP_DIR}/$(basename $PATCHFILE4) $(dirname $PATCHFILE4) >> $LOGFILE 2>>$ERRFILE
        fi
        
        # remove device_xml links
        rm -f ${FIRMWARE_DIR}/${ADDON_NAME}*

        # remove symlink to own js file
        rm -f /www/webui/js/extern/jp_webui_inc.js
        # eigentlich müsste man hier auch JPs neue icons unter /www/ise/img/icons_hm_dis_ep_wm55/24 entfernen
        # aber nur 9..18, 0..8 sind original vorhanden!

        # remove image files
        rm -f /www/config/img/devices/250/$DEVICE_IMG
        rm -f /www/config/img/devices/50/$DEVICE_THUMB
        
    ;;
    
    *)
    ;;
    
esac
